# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='redirect',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
