# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='loc_pos_lat',
            field=models.FloatField(default=41.068178),
        ),
        migrations.AddField(
            model_name='machine',
            name='loc_pos_lon',
            field=models.FloatField(default=28.946577),
        ),
        migrations.AddField(
            model_name='machine',
            name='location_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
