# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0002_auto_20170707_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
